[package]
name = "libawdl-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Capture the air and pull AWDL out of it."

[[bin]]
name = "awdl"
path = "src/main.rs"

[dependencies]
libawdl = { path = "../libawdl" }
libawdl-hal = { path = "../libawdl-hal" }
pcap = "2"
